In [14]:
import pandas as pd
import numpy as np # linear algebra
import pandas as pd # 
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [15]:
df = pd.read_csv("data/simple.csv")

In [16]:
df.head(1)

X   Y
0  1  10

In [17]:
X = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]).reshape(-1, 1)  # Reshape to column vector
Y = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print("X",X)
print("Y",Y)


X [[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
Y [ 10  20  30  40  50  60  70  80  90 100]


In [18]:
X = np.array(df['X']).reshape(-1, 1) 
Y = df['Y']

In [19]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.3,random_state=42)

In [20]:
X_train.shape,X_test.shape, Y_train.shape, Y_test.shape

((7, 1), (3, 1), (7,), (3,))

In [21]:
lr = LinearRegression()

In [22]:
lr.fit(X_train,Y_train)


LinearRegression()

In [23]:
# X_train,Y_train
X_test

array([[9],
       [2],
       [6]], dtype=int64)

In [24]:
y_pred = lr.predict(X_test)
y_pred

array([90., 20., 60.])

In [25]:
r2_score(Y_test,y_pred)

1.0

In [41]:
X = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]).reshape(-1, 1)  # Reshape to column vector
Y = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

mean_X = np.mean(X)
mean_Y = np.mean(Y)
print(mean_X,mean_Y)
# Step 2: Compute covariance between X and Y
covariance = np.mean(X * Y) - mean_X * mean_Y
# print("covariance",np.mean(X * Y))
# # Step 3: Compute variance of X
variance_X = np.var(X)

# # Step 4: Compute slope (m) and intercept (b)
m = covariance / variance_X
b = mean_Y - m * mean_X

# # Step 5: Compute predicted Y values (Y_pred)
Y_pred = m * X + b

# # Step 6: Compute total sum of squares (TSS) and residual sum of squares (RSS)
TSS = np.sum((Y - mean_Y) ** 2)
RSS = np.sum((Y - Y_pred) ** 2)

Y_pred

5.5 55.0


array([[55.],
       [55.],
       [55.],
       [55.],
       [55.],
       [55.],
       [55.],
       [55.],
       [55.],
       [55.]])